import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Hero from "../components/hero/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Custom Next.js starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <section className={styles.section1}>
        <div className="container">
          <h1>First Section</h1>
          <div className={styles.testGrid}>
            <div className={styles.card}>
              <h2>Test</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Adipisci excepturi, recusandae illo rerum perspiciatis omnis.
              </p>
            </div>
            <div className={styles.card}>
              <h2>Test</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Adipisci excepturi, recusandae illo rerum perspiciatis omnis.
              </p>
            </div>
            <div className={styles.card}>
              <h2>Test</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Adipisci excepturi, recusandae illo rerum perspiciatis omnis.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
